# Generated by Django 5.0.3 on 2024-04-10 10:27

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_alter_myscreenshots_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myscreenshots',
            name='screenshot',
            field=cloudinary.models.CloudinaryField(blank=True, default=None, max_length=255, null=True, verbose_name='image'),
        ),
    ]
